# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger: none

pool:
  name: Mac Mini

variables:
  deviceName: "iPhone 13 Pro"

steps:
  # Builds the iOS SDK.
  - script: |
      xcodebuild -scheme CXOneChatSDK \
      -destination 'platform=iOS Simulator,name=$(deviceName)'
    displayName: "Build iOS SDK"

  # Runs the tests defined for the SDK.
  - script: |
      xcodebuild test -scheme CXOneChatSDK \
      -destination 'platform=iOS Simulator,name=$(deviceName)'
    displayName: "Run unit tests"
