# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
  - env/staging

pool:
  name: Mac Mini

jobs:
  # Generates the test coverage for the iOS SDK.
  - job: generate_test_coverage
    steps:
      - task: Xcode@5
        inputs:
          actions: "test"
          scheme: "CXOneChatSDK"
          # The following three items must remain empty in order to function.
          configuration:
          sdk:
          xcWorkspacePath:
          destinationPlatformOption: "iOS"
          destinationSimulators: "iPhone 13 Pro"
          args: "-resultBundlePath test"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: "test.xcresult"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/test.xcresult.zip"
          replaceExistingArchive: true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/test.xcresult.zip"
          ArtifactName: "ios-xcresult"
          publishLocation: "Container"
      - task: CmdLine@2
        inputs:
          script: "xchtmlreport -r test"
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "index.html"
          ArtifactName: "ios-test-results"
          publishLocation: "Container"
